spring:
  cloud:
    config:
      server:
        git:
          # failover: https://github.com/backup-repo/ecom-ms-configs-backup.git
          cache:
            ttl: 60
            
server:
  port: 8888

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info
