spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/** 

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/** 

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka} 
  instance:
    prefer-ip-address: true 

logging:
  level:
    org.springframework.cloud.gateway: DEBUG 

management:
  endpoints:
    web:
      exposure:
        include: health, info
