spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health