spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info